Stuff

diff --git a/.github/workflows/build-natives.yml b/.github/workflows/build-natives.yml
--- a/.github/workflows/build-natives.yml
+++ b/.github/workflows/build-natives.yml
@@ -68,10 +68,13 @@ jobs:
         run: |
           ls D:/a/ihmc-optimizer-wrappers/ihmc-optimizer-wrappers/boost/boost
       - name: Compile native library
-        run: |
-          bash cppbuild.bash
         env:
-          BOOST_ROOT: D:/a/ihmc-optimizer-wrappers/ihmc-optimizer-wrappers/boost/boost
+          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
+          CMAKE_PREFIX_PATH: ${{ steps.install-boost.outputs.BOOST_ROOT }}
+        run: |
+          echo "Using BOOST_ROOT=$BOOST_ROOT"
+          ls "$BOOST_ROOT/include/boost/numeric/ublas/vector.hpp" && echo "ublas found!" || echo "ublas missing"
+          bash cppbuild.bash
       - name: Commit native libraries
         uses: EndBug/add-and-commit@v9
         with:
